menu:
    Blog: /
    Archive: /archives/
    Gallery: /gallery/
    About: /about/

favicon: /favicon.png
logo: /favicon.png

# gallery
user_id: 160709463@N02
api_key: 73bc2a511af797e2a6909f64e00653ec
photoset_id: '72157693734070482'
random: false

# Comment
# e.g disqus: seansun
disqus: petingo
duoshuo:

# Analytics
google-analytics:
ga: UA-119801105-1

# Copyright Infomation
startyear: 2018
