menu:
    Blog: /
    Archive: /archives/
    Gallery: /gallery/
    About: /about/

favicon: /favicon.png
logo: /favicon.png

# gallery
source: flickr
user_id: xxxxxxxxx@Xxx
api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
photoset_id: 'xxxxxxxxxxxxxxxxx'
random: true

# Comment
# e.g disqus: seansun
disqus: 
duoshuo:

# Analytics
google-analytics:
ga: UA-xxxxxxxxx-1

# Copyright Infomation
startyear: 2018
